create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists public.app_runtime_controls (
  id text primary key,
  writes_frozen boolean not null default false,
  message text not null default '',
  changed_at timestamptz not null default now(),
  changed_by text not null default ''
);

create table if not exists public.app_runtime_control_events (
  id bigint generated by default as identity primary key,
  writes_frozen boolean not null,
  message text not null default '',
  incident_reference text not null default '',
  changed_at timestamptz not null default now(),
  changed_by text not null default ''
);

insert into public.app_runtime_controls (id, writes_frozen, message, changed_by)
values ('application', false, '', 'migration')
on conflict (id) do nothing;

alter table public.app_runtime_controls enable row level security;
alter table public.app_runtime_control_events enable row level security;
revoke all on public.app_runtime_controls, public.app_runtime_control_events from public, anon, authenticated;
grant select on public.app_runtime_controls, public.app_runtime_control_events to service_role;

create or replace function public.app_writes_frozen()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((
    select control.writes_frozen
    from public.app_runtime_controls control
    where control.id = 'application'
  ), false)
$$;

create or replace function public.get_app_runtime_status()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'writesFrozen', control.writes_frozen,
    'message', control.message,
    'changedAt', control.changed_at
  )
  from public.app_runtime_controls control
  where control.id = 'application'
$$;

create or replace function public.set_app_write_freeze(
  p_enabled boolean,
  p_message text default '',
  p_incident_reference text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  request_role text := coalesce(auth.role(), '');
  actor text := coalesce(nullif(auth.jwt()->>'email', ''), nullif(request_role, ''), session_user::text);
  safe_message text := case
    when p_enabled then left(coalesce(nullif(btrim(p_message), ''), 'Project Tracker is temporarily read-only while maintenance is in progress.'), 300)
    else ''
  end;
  safe_incident_reference text := left(coalesce(btrim(p_incident_reference), ''), 120);
begin
  if request_role <> 'service_role' and session_user not in ('postgres', 'supabase_admin') then
    raise exception 'Only an authorized recovery operator can change the application write freeze.'
      using errcode = '42501';
  end if;

  update public.app_runtime_controls
  set writes_frozen = p_enabled,
      message = safe_message,
      changed_at = now(),
      changed_by = actor
  where id = 'application';

  insert into public.app_runtime_control_events (
    writes_frozen,
    message,
    incident_reference,
    changed_by
  ) values (
    p_enabled,
    safe_message,
    safe_incident_reference,
    actor
  );

  return public.get_app_runtime_status();
end;
$$;

create or replace function private.enforce_application_write_freeze()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  request_role text := coalesce(
    nullif(auth.role(), ''),
    nullif(current_setting('role', true), 'none'),
    ''
  );
  maintenance_message text;
begin
  if request_role not in ('anon', 'authenticated') then
    return null;
  end if;

  select control.message
  into maintenance_message
  from public.app_runtime_controls control
  where control.id = 'application'
    and control.writes_frozen;

  if found then
    raise exception 'APP_WRITES_FROZEN'
      using
        errcode = '55000',
        detail = maintenance_message,
        hint = 'Reads remain available. Retry the change after maintenance ends.';
  end if;

  return null;
end;
$$;

revoke all on function public.app_writes_frozen() from public;
revoke all on function public.get_app_runtime_status() from public;
revoke all on function public.set_app_write_freeze(boolean, text, text) from public, anon, authenticated;
revoke all on function private.enforce_application_write_freeze() from public, anon, authenticated;
grant execute on function public.app_writes_frozen() to anon, authenticated, service_role;
grant execute on function public.get_app_runtime_status() to anon, authenticated, service_role;
grant execute on function public.set_app_write_freeze(boolean, text, text) to service_role;

do $$
declare
  target_table record;
begin
  for target_table in
    select format('%I.%I', table_schema, table_name) as qualified_name
    from information_schema.tables
    where table_schema = 'public'
      and table_type = 'BASE TABLE'
      and table_name <> 'app_runtime_controls'
  loop
    execute format(
      'drop trigger if exists enforce_application_write_freeze on %s',
      target_table.qualified_name
    );
    execute format(
      'create trigger enforce_application_write_freeze before insert or update or delete on %s for each statement execute function private.enforce_application_write_freeze()',
      target_table.qualified_name
    );
  end loop;
end;
$$;

drop policy if exists "Application maintenance permits storage inserts" on storage.objects;
create policy "Application maintenance permits storage inserts"
  on storage.objects as restrictive for insert to anon, authenticated
  with check (not (select public.app_writes_frozen()));

drop policy if exists "Application maintenance permits storage updates" on storage.objects;
create policy "Application maintenance permits storage updates"
  on storage.objects as restrictive for update to anon, authenticated
  using (not (select public.app_writes_frozen()))
  with check (not (select public.app_writes_frozen()));

drop policy if exists "Application maintenance permits storage deletes" on storage.objects;
create policy "Application maintenance permits storage deletes"
  on storage.objects as restrictive for delete to anon, authenticated
  using (not (select public.app_writes_frozen()));
