create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor_user_id uuid,
  actor_email text not null default '',
  entity_type text not null check (entity_type in ('project', 'task')),
  entity_id text not null,
  project_id text not null default '',
  action text not null check (action in ('insert', 'update', 'delete')),
  before_data jsonb,
  after_data jsonb
);

create index if not exists audit_events_created_at_idx on public.audit_events (created_at desc);
create index if not exists audit_events_project_id_idx on public.audit_events (project_id, created_at desc);
create index if not exists audit_events_entity_idx on public.audit_events (entity_type, entity_id, created_at desc);

alter table public.audit_events enable row level security;

drop policy if exists "Authenticated users can read audit events" on public.audit_events;
create policy "Authenticated users can read audit events"
  on public.audit_events for select
  to authenticated
  using (
    exists (
      select 1
      from public.settings app_settings,
        jsonb_array_elements(coalesce(app_settings.data->'users', '[]'::jsonb)) app_user
      where app_settings.id = 'app_settings'
        and lower(coalesce(app_user->>'email', '')) = lower(coalesce(auth.jwt()->>'email', ''))
        and app_user->>'role' = 'Admin'
    )
  );

revoke insert, update, delete on public.audit_events from anon, authenticated;
grant select on public.audit_events to authenticated;

create or replace function public.record_tracker_audit_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  old_data jsonb := case when tg_op = 'INSERT' then null else old.data end;
  new_data jsonb := case when tg_op = 'DELETE' then null else new.data end;
  target_data jsonb := coalesce(new_data, old_data, '{}'::jsonb);
  target_id text := coalesce(new.id, old.id);
  target_type text := case when tg_table_name = 'projects' then 'project' else 'task' end;
  target_project_id text := case
    when tg_table_name = 'projects' then target_id
    else coalesce(target_data->>'projectId', '')
  end;
begin
  if tg_op = 'UPDATE' and old_data is not distinct from new_data then
    return new;
  end if;

  insert into public.audit_events (
    actor_user_id,
    actor_email,
    entity_type,
    entity_id,
    project_id,
    action,
    before_data,
    after_data
  ) values (
    auth.uid(),
    coalesce(auth.jwt()->>'email', ''),
    target_type,
    target_id,
    target_project_id,
    lower(tg_op),
    old_data,
    new_data
  );

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists projects_audit_trigger on public.projects;
create trigger projects_audit_trigger
after insert or update or delete on public.projects
for each row execute function public.record_tracker_audit_event();

drop trigger if exists tasks_audit_trigger on public.tasks;
create trigger tasks_audit_trigger
after insert or update or delete on public.tasks
for each row execute function public.record_tracker_audit_event();
